import type { Metadata } from "next";
import AboutPage from "@/pages/AboutPage";

export const metadata: Metadata = {
  title: "Hruday Kumar - Personal Portfolio",
  description: "Generated by create next app",
};

const About = () => {
  return (
    <div>
      <AboutPage />
    </div>
  );
};

export default About;
