import ContactusPage from "@/pages/Contactus";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Hruday Kumar - Personal Portfolio",
  description: "Generated by create next app",
};

const ContactUs = () => {
  return (
    <div>
      <ContactusPage />
    </div>
  );
};

export default ContactUs;
