import type { Metadata } from "next";
import { Manrope, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import BacktoTop from "@/components/BacktoTop";
import { ThemeProvider } from "@/context/ThemeContext";
import { AlertContextProvider } from "@/context/AlertContext";
import Alerts from "@/components/Alerts";
import ParticlesComponent from "@/components/Particles";
import ChatBot from "@/components/ChatBot";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-monteserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hruday Kumar - Personal Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${manrope.variable} antialiased`}
      >
        <AlertContextProvider>
          <ThemeProvider>
            <Alerts />
            <Header />
            <ParticlesComponent id="particles" />
            {children}
            <ChatBot />
            <BacktoTop />
          </ThemeProvider>
        </AlertContextProvider>
      </body>
    </html>
  );
}
