import type { Metadata } from "next";
import HomePage from "@/pages/HomePage";

export const metadata: Metadata = {
  title: "Hruday Kumar - Personal Portfolio",
  description: "Generated by create next app",
};

const Home = () => {
  return (
    <>
      <HomePage />
    </>
  );
};

export default Home;
