import type { Metadata } from "next";
import HomePage from "@/pages/HomePage";

export const metadata: Metadata = {
  title: "Hruday Kumar - Personal Portfolio",
  description: "Generated by create next app",
};

const Home = () => {
  return (
    <div className="min-h-screen w-full">
      <HomePage />
    </div>
  );
};

export default Home;
