import type { Metadata } from "next";
import ServicesPage from "@/pages/ServicesPage";
export const metadata: Metadata = {
  title: "Hruday Kumar - Personal Portfolio",
  description: "Generated by create next app",
};

const Services = () => {
  return (
    <div>
      <ServicesPage />
    </div>
  );
};

export default Services;
